import './scss/main.scss';
import './vendor/animate.css';
import './js/main.js';
import logo from './images/svg-icons/baby-cartoon-cute-fork-spoon-svgrepo-com.svg';
import search from './images/svg-icons/search.svg';
import topImage from './images/top-image.jpg'; 
import bgPaint from './images/bg-paint-top.png';
import chesnok from './images/chesnok.png';
import chili from './images/chili.png';
import onion from './images/onion.png';
import perech from './images/perech.png';
import tomat from './images/tomat.png';
import vetka from './images/vetka.png';
import headerDecoration from './blocks/header/__decoration/js/header__decoration.js';
import list from './images/svg-icons/list.svg';
import headerNavListButton from './blocks/header/__nav-list-button/js/header__nav-list-button.js';
import headerNavSearch from './blocks/header/__nav-search/js/header__nav-search.js';
import bestSeller1 from './images/best-seller-1.jpg';
import bestSeller2 from './images/best-seller-2.jpg';
import bestSeller3 from './images/best-seller-3.jpg';
import bestSeller4 from './images/best-seller-4.jpg';
import bgPaint1 from './images/bg-paint-orinteal-taste.png';