import './scss/main.scss';
import './js/main.js';
import titleSectionImg from './images/title-section-img.jpg';
import instagram from './images/icons/instagram.svg';
import telegram from './images/icons/telegram.svg';
import vk from './images/icons/vk.svg';
import whatsapp from './images/icons/whatsapp.svg';
import certificate1 from './images/icons/certificate-1.svg';
import certificate2 from './images/icons/certificate-2.svg';
import psychologist from './images/icons/psychologist.svg';
import './blocks/preview-block/__info-button/js/preview-block__info-button.js';
import depressia from './images/depressia.jpg';
import fobii from './images/fobii.jpg';
import hypno from './images/hypno.jpg';
import nevroz from './images/nevroz.jpg';
import panick from './images/panick.jpg';
import samootsenka from './images/samootsenka.jpg';
import './blocks/attendances-block/__button/js/attendances-block__button.js';
import './blocks/sing-up-block/__select-method/js/sing-up-block__select-method.js';
import './blocks/sing-up-block/__close/js/sing-up-block__close.js';
import './vendor/wowjs/css/libs/animate.css';
import WOW from './vendor/wowjs/dist/wow.js';
import './js/main.js';
import icon from './images/icons/favicon.ico';
import icon16 from './images/icons/favicon-16x16.png';
import icon32 from './images/icons/favicon-32x32.png';
import icon96 from './images/icons/favicon-96x96.png';
import icon120 from './images/icons/favicon-120x120.png';
import icon192 from './images/icons/favicon-192x192.png';